### ISSUE TITLE
Engine and Demo Crash w/ Logitech Audio Device

### ISSUE THREAD

**Issue by BATTLESQUATCH** [kwstasg/WAC#3]
I have two audio devices - surround sound setup and Logitech G430 headset.  In both 4.15 and 4.17 versions, trying to play in editor or launch the 4.15 demo build with my default audio device set as the Logitech G430 headset causes a crash.  Playing in editor or launching the demo project and picking a map works fine with my surround sound.  

Drivers for the headset are up to date, I've tried disabling Logitech Gaming Software and forcing end task for Realtek HD audio manager, but nothing seems to resolve this issue.  

This is a really great plugin and I've had a lot of fun playing around with modifying the spectrum analyzer.  I'm just sort of at a loss as to how to troubleshoot and/or resolve this issue.  The crash report doesn't give any information as to what's causing it and I've tried other audio devices (HDMI monitor speakers) and none of those cause a crash.  Any insight would be super appreciated.  Thanks for your time!

**Comment by AaronTrotter** [comment]
Did you ever get any further with this @butt3rs ?

**Comment by kabassmusic** [comment]
I know this is super old but one of our players encountered this issue as well with a Logitech Gaming Headset. Unplugging the headset works fine. Plugging in after WAC executes works fine as well. 

The error I get is because of this:
AudioListener::AudioListener(int BitsPerSample, int FormatTag, int BlockAlign, int XSize)

I think the loopback section is causing the crash to happen.
